### PR TITLE
Add support for clang-format-17

### PR DESCRIPTION
**Pull request by Xav83**
Hi @jidicula,

I am creating this Pull Request in relation with the issue #162 :slightly_smiling_face:  (and in the context of Hacktoberfest 2023). 
I've inspired myself a lot from the Pull Requests you have linked in the issue description.

Currently, I am trying to run the script `test/test.sh` like you mentioned in the [CONTRIBUTING](https://github.com/jidicula/clang-format-action/blob/main/CONTRIBUTING.md), but I am currently having the following error:

```
Unable to find image 'ghcr.io/jidicula/clang-format:17' locally
``` 

and,

```shell
$ docker pull ghcr.io/jidicula/clang-format:17
Error response from daemon: manifest unknown
```

Maybe GitHub Actions will have the right setup, and not have this issue.
Until GitHub Actions gives me some results, I'll continue seeing if I can solve this issue on my end :wink:

### CODE REVIEW

**Review by jidicula — CHANGES_REQUESTED** [review]
Thanks for submitting a PR! Could you split your changes in `.github/workflows/clang-format-image.yml` into a separate PR? Then I can approve and merge that and the new version image will start getting built and published to this repo's container registry, and this PR will be able to pull down that image and its tests will pass.

It's a bit convoluted but that's because I only allow image publish upon merge into `main`, not from PRs.

**Comment by Xav83** [comment]
Ok @jidicula ! I'm creating the other Pull request right now :wink:

**Comment by Xav83** [comment]
So, @jidicula, this is the PR #164 :slightly_smiling_face:

**Review by jidicula — APPROVED** [review]
Alright, looks like CI is passing! Thank you for your contribution 😁

**Pull request merged**
