### PR TITLE
Add support for proto/pb files

### PR DESCRIPTION
**Pull request by madninja**
This adds support for protobuf files extensions `.proto`.

Used here: https://github.com/helium/proto

### CODE REVIEW

**Comment by glebm** [comment]
`.proto` is usually used for schema, while `.textproto` is usually used for the text format.
`.pb` is generally used for the wire-format (binary) protos

**Comment by madninja** [comment]
I haven't forgotten about this! The repo states to _either_ add a test or show it being used in another repo which I did provide. 

I can add the test cases, just need to find a bit of time

**Comment by glebm** [comment]
@madninja I came across this by accident and just wanted to point out that `.pb` should be `.textproto` instead!

**Comment by madninja** [comment]
> @madninja I came across this by accident and just wanted to point out that `.pb` should be `.textproto` instead, as `.pb` is generally used for binary-format files that shouldn't be formatted. No rush!

I’ve never heard of or seen .textproto as the extension for protobuf source files. Google documentation indicates the recommended file extensions for source files, which we should follow here

**Comment by glebm** [comment]
Can you please provide a link to that Google documentation?

**Comment by madninja** [comment]
> Can you please provide a link to that Google documentation?

The pb extension is not documented at all.. the recommended file structure is [here](https://developers.google.com/protocol-buffers/docs/style#file_structure)

**Comment by glebm** [comment]
The only extension for proto **schema** is `.proto`.

The canonical extension for textproto **data** is `.textproto`. Two other *deprecated* extensions also exist: `.pbtxt` and `.text_proto`.

The canonical extension for the binary (aka "wire-format") **data** is `.pb`.

The source for this is internal Google documentation.

**Comment by madninja** [comment]
> The source for this is internal Google documentation. I also couldn't find a public source.

Well that's unfortunate.. Either way, for this PR we can use just `.proto` as checked extensions and supply tests for those, since that's presumably the majority use case

**Comment by jidicula** [comment]
> > The source for this is internal Google documentation. I also couldn't find a public source.
> 
> Well that's unfortunate.. Either way, for this PR we can use just `.proto` as checked extensions and supply tests for those, since that's presumably the majority use case

Yeah, I have no strong feelings either way. I think at some point I may generalize this Action more to accept a custom regex to support arbitrary file extensions. When I started on this, I didn't know that `clang-format` can be used for languages other than C and C++ 😁.

@glebm if you want to include this change, you can submit another PR following this merge to simplify integration.

**Pull request merged**
