### PR TITLE
added container testing

### LINKED ISSUE #51: add unit testing
How about adding a simple github action for testing the docker container and it's script by simply building the container and running the script on some test data? Like a hello-world.cpp? That would make sure that the script and container is working fine for every PR.

### PR DESCRIPTION
**Pull request by staxfur**
This PR adds testing for the docker container and it's script. Fixes #51.

Currently a draft because #52 must be merged first in order to the new action to succeed.

Also note that the first run must fail in order to verify that the source file was correctly checked against it's formating.

### CODE REVIEW

**Comment by jidicula** [comment]
> @jidicula how would you prefer it?
> 
> * cloning the repo in the action yml
> * adding the testing repo as git submodule
> * copying the files from your testing repo over here into the tests/ folder

My apologies, I think my old comment draft was submitted along with my edit of it. The last option would be best, I think, and then I'll delete my testing repo. It makes more sense to me to have the testing files in the same repo as the Action.

**Comment by MCWertGaming** [comment]
Sure! Will do that quickly

**Comment by MCWertGaming** [comment]
Local fix is done @jidicula but cant test it before #51 is merged because the dockerfile is broken.

**Comment by MCWertGaming** [comment]
Uplodaded your testing files now! And created a small script because the failing tests would make the ci task fail when called directly!

**Comment by MCWertGaming** [comment]
All done now, waiting for #52 to be merged for the needed rebase!

**Pull request merged**
